# Generated by Django 2.1.1 on 2019-05-06 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=255)),
                ('dia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('luces', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedesProyecto.Salon'),
        ),
        migrations.AddField(
            model_name='horario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
